import = [
	"~/.config/alacritty/themes/catppuccin.toml"
]

[window]

padding.x = 10
padding.y = 10

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 15

[shell]
program = "/opt/homebrew/bin/fish"
